### ISSUE TITLE
Alias method #cancel on Subscription

### ISSUE THREAD

**Issue by KevinSjoberg** [avdi/brainguy#3]
First of all, thanks for taking the time to build this library. It's really neat and I really appreciate all effort you've put in.

Recently, I've done some work in Java using [RxJava](https://github.com/ReactiveX/RxJava). It's a Java implementation of [ReactiveX](http://reactivex.io/). They have named the cancellation of a subsctiption, `unsubscribe`. I've seen this naming for a few other libraries as well.

Naturally, I fiddled around with brainguy and tried to call `#unsubscribe` on the subscription. But it didn't work since it's called `#cancel`. I was wondering what you think about creating an alias, `#unsubscribe` for `Subscription#cancel`? It could be a nice win for others assuming the same API as with other Observer implementations.

**Comment by avdi** [comment]
Excellent question. BTW, I'm interested in possibly building an Rx library
on top of this at some point.

I'm not completely opposed to such an alias. But I have some initial
reluctance, which I'll explain:

I was very particular about naming it `#cancel`. I thought about "what
would I say *to a Subscription* to tell it to stop being subscribed?". And
I realized that when I have a subscription to a magazine, when I don't want
to receive it anymore I "cancel" the subscription.

In RxJava, is the `unsubscribe()` method on a Subscription object, or is it
on the thing that manages subscriptions?

**Comment by KevinSjoberg** [comment]
Building a Rx library on top of brainguy sounds awesome. I'd love to help out if you want to.

I agree with what you're saying. If we're looking at this in forms of "sending a message", `#cancel` is definitely the proper naming (You're cancelling your subscription). In RxJava the `unsubscribe()` method is on the `Subscription` object. See the [documentation](http://reactivex.io/RxJava/javadoc/rx/Subscription.html).

**Comment by avdi** [comment]
So I *think* what I want to do is put this ticket on back-burner, and see if it is a sticking point for anyone else. I'm a fan of Ruby's habit of making aliases to make APIs more accessible (e.g. collect/reduce), but at the same time I don't want to bulk up the API early.

Sound OK?

And some help on the Rx stuff would be awesome. I've only barely begun to think about it; want to make sure this is nice and stable first.

**Comment by KevinSjoberg** [comment]
Yeah, sounds good to me! It's definitely not a deal breaker in any way.

Great, feel free to reach out when it's time. :smile:
